index:
    path: /teacher
    controller: App\Controller\TeacherController::index
showTeacher:
    path: /show/{name}/{id}
    controller: App\Controller\TeacherController::showTeacher
showAuthor:
    path: /show/{name}
    controller: App\Controller\AuthorController::showAuthor
list:
    path: /list
    controller: App\Controller\AuthorController::list
authorDetails:
    path: /authorDetails/{id}
    controller: App\Controller\AuthorController::authorDetails
addBook:
    path: /addBook
    controller: App\Controller\BookController::addBook
addAuthor:
    path: /addAuthor
    controller: App\Controller\AuthorController::addAuthor
getBooks:
    path: /book/getAll
    controller: App\Controller\BookController::/book/getAll